services:
    postgres:
        container_name: roshambo-db
        image: postgres:15
        environment:
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: password
            PG_DATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
    roshambo:
        container_name: roshambo
        image: maslyna/rock-paper-scissors:1.0-SNAPSHOT
        environment:
            DB_URL: r2dbc:postgresql://roshambo-db:5432/sa
            DB_USER: sa
            DB_PASSWORD: password
            FLYWAY_DB_URL: jdbc:postgresql://roshambo-db:5432/sa
            FLYWAY_DB_USER: sa
            FLYWAY_DB_PASSWORD: password
        ports:
            - "8080:8080"
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge
volumes:
    postgres:
    pgadmin: