spring:
    application:
        name: roshambo
    r2dbc:
        url: ${DB_URL:r2dbc:postgresql://localhost:5432/sa}
        username: ${DB_USER:sa}
        password: ${DB_PASSWORD:password}
    flyway:
        enabled: true
        url: ${FLYWAY_DB_URL:jdbc:postgresql://localhost:5432/sa}
        user: ${FLYWAY_DB_USER:sa}
        password: ${FLYWAY_DB_PASSWORD:password}


server:
    port: ${SERVER_PORT:8080}
